### ISSUE TITLE
[BUG] docker-compose fails with "read .env: is a directory" when .env is a directory and --env-file is not specified

### ISSUE THREAD

**Issue by smnscp** [docker/compose#10430]
### Description

`docker compose` fails with "read .env: is a directory" when .env is a directory and --env-file is not specified.

I think, this is a regression of https://github.com/docker/compose/issues/8703 that was re-introduced with https://github.com/compose-spec/compose-go/commit/a3b22bd971f39bb12d583bb97f38ce7bf490366a.

### Steps To Reproduce

```bash
mkdir temp
cd temp
echo "services:" > docker-compose.yml # Just a minimal config.
mkdir .env
docker compose up
# read ~/temp/.env: is a directory
```
Circumvent this error by specifying an env file:
```bash
touch .env-docker
docker compose --env-file .env-docker up
# services must be a mapping
```
The above message is expected since the `services` property is empty.

### Compose Version

```Text
Docker Compose version 2.17.2
```

### Docker Environment

```Text
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.3)
  compose: Docker Compose (Docker Inc., 2.17.2)
  dev: Docker Dev Environments (Docker Inc., v0.1.0)
  extension: Manages Docker extensions (Docker Inc., v0.2.18)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.25.0)
  scout: Command line tool for Docker Scout (Docker Inc., v0.6.0)
```

### Anything else?

I suggest, before [appending the default `.env` to the empty list of env-files](https://github.com/compose-spec/compose-go/commit/a3b22bd971f39bb12d583bb97f38ce7bf490366a#diff-0953236283edf016dbef569cb026a05dba9df5e7934af11b82499e3bec8fe006R227-R228) the existence of that _file_ should be checked.

**Comment by jturmel** [comment]
This is also affecting some of our projects after upgrading Docker, we store various env files in .env directory, these were never intended or Docker but now Docker doesn't like that we have a .env folder

**Comment by smnscp** [comment]
@jturmel 

> This is also affecting some of our projects

The easiest way to mitigate this for the time being is:
```
docker compose --env-file /dev/null
```

Thanks to @ndeloof the next Docker update will probably contain the fix.

**Comment by milas** [comment]
A fix for this is in compose-spec/compose-go#383.

We're planning on tagging a new version of that for inclusion in the next Compose release, so this should be fixed then. Thanks for the report!

**Comment by Salaah01** [comment]
Justification for this change?

**Comment by ndeloof** [comment]
@Salaah01 was not intentional, issue was re-introduced after some refactoring

**Comment by theoratkin** [comment]
It seems this issue is back in 2.37.0, and specifying `--env-file` doesn't help.

EDIT: After further investigation, it seems to happen only under certain circumstances, such as using `--build`. I will try to create a minimal reproduction config and create a new issue.
