### ISSUE TITLE
[BUG] `.env` file relative to command location instead of project

### ISSUE THREAD

**Issue by ifellinaholeonce** [docker/compose#11531]
### Description

We have a project with multiple submodules all within an orchestration directory. We recently updated Docker (Docker Desktop Mac version to`v4.27.2` from `4.25.1`) and have noticed a change in how our `.env` is loaded during build.

Dir Structure
```
/orchestration/
 - submodule1/
   - app/
   - Dockerfile
   - .env
 - submodule2/
   - app/
   - Dockerfile
   - .env
 - docker-compose.yml
 - .env 
```
docker-compose.yml
```
version: "3"
services:
  api:
    extends:
      file: common-services.yml
      service: api_common
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
 ```
common-services.yml
```
version: "3"
services:
  api_common:
    image: api:latest
    build:
      context: submodule1
      args:
        MY_VAR: ${MY_VAR}
    environment:
      - PGUSER=${USER:-postgres}
      - PGHOST=postgres
      - PGPORT=5432
      - REDIS_URL=redis://redis:6379
    env_file:
      - submodule1/.env
      - submodule1/.env.shared

```

Previously we were able to run `docker-compose build` from any of the subdirectories and `MY_VAR` was correctly read from `orchestration/.env`. However, since updating to `v4.27.2` this variable will only be set if the command is run from `orchestration` and not from within a submodule.

Is this change in behaviour expected? Is there anyway we can get this back?

### Compose Version

```Text
Docker Compose version v2.24.5-desktop.1
```

### Docker Environment

```Text
Client:
 Version:    25.0.3
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.1-desktop.4
    Path:     /Users/tymm/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.24.5-desktop.1
    Path:     /Users/tymm/.docker/cli-plugins/docker-compose
  debug: Get a shell into any image or container. (Docker Inc.)
    Version:  0.0.24
    Path:     /Users/tymm/.docker/cli-plugins/docker-debug
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.21
    Path:     /Users/tymm/.docker/cli-plugins/docker-extension
  feedback: Provide feedback, right in your terminal! (Docker Inc.)
    Version:  v1.0.4
    Path:     /Users/tymm/.docker/cli-plugins/docker-feedback
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v1.0.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/tymm/.docker/cli-plugins/docker-sbom
  scout: Docker Scout (Docker Inc.)
    Version:  v1.4.1
    Path:     /Users/tymm/.docker/cli-plugins/docker-scout
WARNING: Plugin "/Users/tymm/.docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /Users/tymm/.docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 25.0.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc version: v1.1.12-0-g51d5e94
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.6.12-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 8
 Total Memory: 7.658GiB
 Name: docker-desktop
 ID: cb5d60aa-25d0-476b-8aac-40e4ba6f509f
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by matthewbordas** [comment]
I am also seeing this issue. We only have a root level `.env` in our project, next to our `docker-compose.yml`, but now it's looking for a `.env` in a sub-project's directory so the environment variables are getting logged as warnings for not being set:
```sh
WARN[0000] The "DB_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_HOST" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string.
WARN[0000] The "DB_DATABASE" variable is not set. Defaulting to a blank string.
```

This is causing major issues with our setup now.

**Comment by MikaelElkiaer** [comment]
I am experiencing the exact same, broken as of updating this morning.

@matthewbordas Not sure what you mean with it looking for a sub-project's directory - how are you determining this? And could this be a potential workaround for now?

**Comment by ifellinaholeonce** [comment]
@MikaelElkiaer not to speak for matthewbordas but my experience sounds similar. If I run the build command from within a submodule directory, docker compose reads the `.env` file from within that directory instead of the directory where the `docker-compose` file is found.
So for me (and it sounds like for matthewbordas as well) this results in the environment variable not being set and logging warnings as above.

**Comment by matthewbordas** [comment]
@ifellinaholeonce thanks, that is what I meant. @MikaelElkiaer I updated my message to be clearer. Does that make sense now?

**Comment by MikaelElkiaer** [comment]
Thanks @ifellinaholeonce and @matthewbordas.

I see my case is a slightly different variation.
I have the structure:

```
/project
├── /compose
│   └── docker-compose.yaml
└── .env
```

Where my `.env` has the contents:

```bash
COMPOSE_FILE=./compose/docker-compose.yaml
COMPOSE_PATH_SEPARATOR=:
```

In order to separate compose from rest of the project folders, while still being able to use `docker compose` from project root.

**Comment by ndeloof** [comment]
This has been fixed in latest release [v2.24.6](https://github.com/docker/compose/releases/tag/v2.24.6) by https://github.com/docker/compose/pull/11405

you can install this release by downloading binary for your platform under `$HOME/.docker/cli-plugins/docker-compose`)

**Comment by matthewbordas** [comment]
@ndeloof great news, thank you! I'd prefer to install this alongside a Docker Desktop update if possible since that's my current workflow. What's the typical release schedule?

**Comment by ClaytonPassmore** [comment]
FYI - Looks like v4.28.0 of docker desktop for Mac is bundled with the patched version of compose 🥳

**Comment by MikaelElkiaer** [comment]
It seems my issue is still not solved, but at least now I know what is wrong.
It seems there is another regression following v2.24.4 - as `docker compose` now looks in parent folders for a `docker-compose.yaml`, rather than adhering to `.env` values first (where I set `COMPOSE_FILE`).
