### ISSUE TITLE
[BUG] `docker-compose run` not start other depend_on services after upgrade to 2.32.0

### ISSUE THREAD

**Issue by lulala1126** [docker/compose#12421]
### Description

we have a docker-compose.yml are like:
```
version: "3"
services:
  base:
    build:
      context: .
    environment:
      - NGINX_ENABLE_BROTLI
      - NGINX_CORS_ENABLED
     ……

  test:
    extends: base
    volumes:
      - ./tests:/tests
    build:
      dockerfile: Dockerfile.client
    depends_on: [proxy]

  proxy:
    extends: base
    build:
      args:
        - ENABLED_MODULES=brotli
    depends_on: [nginx_a, nginx_b]
    environment:
      - NGINX_BACKEND=nginx_a:80
 ……
    volumes:
      - ./tests/fixture/:/app/data/assets/
      - ./tests/fixture/:/app/public/packs/


  nginx_a:
    image: nginx:1.27.3-alpine@sha256:41523187cf7d7a2f2677a80609d9caa14388bf5c1fbca9c410ba3de602aaaab4
    volumes:
      - ./tests/setup/test.conf:/etc/nginx/conf.d/test.conf
      - ./README.md:/usr/share/nginx/html/deny/test

  nginx_b:
    image: nginx:1.27.3-alpine@sha256:41523187cf7d7a2f2677a80609d9caa14388bf5c1fbca9c410ba3de602aaaab4
    volumes:
      - ./README.md:/usr/share/nginx/html/test/test
```

and we will run the docker-compose using this script: `docker-compose run test tests/${CASE}/cases`.

when we ran this command with the docker-compose version 2.31.0, the command succeeded and started all services.  like:
![Image](https://github.com/user-attachments/assets/8ad12fbc-b214-4af4-8722-c45fe2d67a3d)

But after we upgrade to v2.32.0, the command are not start other [proxy, nginx_a,nginx_b] services, so the text failed, like:
<img width="1476" alt="Image" src="https://github.com/user-attachments/assets/184f29ed-b020-4296-957f-88164ecf75e7" />

### Compose Version

```Text
2.32.1
```

### Docker Environment

```Text
Client:
 Context:    colima
 Debug Mode: false

Server:
 Containers: 246
  Running: 15
  Paused: 0
  Stopped: 231
 Images: 126
 Server Version: 24.0.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dd1e886e55dd695541fdcd67420c2888645a495
 runc version: v1.1.10-0-g18a0cb0
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.5.0-44-generic
 Operating System: Ubuntu 23.10
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 7.737GiB
 Name: colima
 ID: f77e530b-9674-4cae-a778-502504dd68cb
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: lula1126
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by alxant** [comment]
I confirm, it has definitely broken.

**Comment by idsulik** [comment]
it was fixed here https://github.com/compose-spec/compose-go/pull/721, need to wait for the next release.
@glours , I think we need a release with the fix, many issues related to the bug ![Image](https://github.com/user-attachments/assets/c3227496-cb24-43f7-b763-026dd3be99f1)

**Comment by glours** [comment]
@idsulik sorry holidays here for Nicolas and myself, it will have to wait early January.
During this time, I suggest to switch back to the Compose's previous version.

**Comment by idsulik** [comment]
@glours Thanks for the update. Enjoy the holidays!)

**Comment by exos** [comment]
Temporary fix in Archlinux:

```
$ wget https://archive.archlinux.org/packages/d/docker-compose/docker-compose-2.31.0-1-x86_64.pkg.tar.zst
$ wget https://archive.archlinux.org/packages/d/docker-compose/docker-compose-2.31.0-1-x86_64.pkg.tar.zst.sig
$ pacman-key --verify docker-compose-2.31.0-1-x86_64.pkg.tar.zst.sig
$ sudo pacman -U ./docker-compose-2.31.0-1-x86_64.pkg.tar.zst.sig
```

**Comment by snaggen** [comment]
Version 2.32.3 should contains the fix, but it still doesn't work to have both depends_on and extends

**Comment by buxm** [comment]
I confirm that the bug has **not** yet been fixed, also in version 2.32.4.
