### ISSUE TITLE
SSL error while trying to pull image on Ubuntu

### ISSUE THREAD

**Issue by phlegx** [docker/compose#1319]
With the current version (1.2.0 with Docker 1.6.0 on ubuntu trusty ) when trying to run the image like:

```docker-compose run application_name```

 I'm getting the following error. 

```HTTPS endpoint unresponsive and insecure mode isn't enabled```

The SSL certificate however is valid and the URL is correct. This is my very basic configuration:

```
web:
   image: example.com/application_name:latest
```

With docker run it pulls the image just fine:

```docker run example.com/application_name:latest```

Any ideas what might be causing this?

**Comment by phlegx** [comment]
Tried out also the 1.2.0rc4 version. Still the same problem it seems.

I also tried the flag

``` 
--allow-insecure-registry
```

as suggested here: #1136, that didn't resolve the issue either.

**Comment by antoineco** [comment]
I use a [recent built of `master`](https://github.com/antoineco/compose/releases) and the error persists. Shouldn't it be fixed by 1dccd58209a61b4001a7034c5e0b7472fc6878f9?

The `--allow-insecure-ssl` flag works but is definitely not a solution, we use a certificate signed from Comodo.

```
Pulling web (docker.example.com/web:master)...
/tmp/_MEIt87UgO/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 470, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 333, in execute_convergence_plan
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 380, in recreate_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 209, in create_container
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 237, in ensure_image_exists
  File "/code/build/docker-compose/out00-PYZ.pyz/compose.service", line 707, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.client", line 876, in pull
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 59, in resolve_repository_name
  File "/code/build/docker-compose/out00-PYZ.pyz/docker.auth.auth", line 38, in expand_registry_url
docker.errors.DockerException: HTTPS endpoint unresponsive and insecure mode isn't enabled.
```

**Comment by aanand** [comment]
Fixed by #1736 and released in [Compose 1.4.0 RC2](https://github.com/docker/compose/releases/tag/1.4.0rc2).

**Comment by MrMMorris** [comment]
@aanand 
`$ docker-compose -v`
`docker-compose version: 1.4.0rc2`

`$ pip list | grep docker-py`                                                                            
`docker-py (1.3.1)`

`/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.`

Am I missing something?

**Comment by aanand** [comment]
@MrMMorris I presume you installed Compose with Pip. What's your Python version? You'll get that error if you're on a version older than 2.7.9, because the `ssl` module is insecure (see the [linked documentation](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning)).

**Comment by MrMMorris** [comment]
@aanand my python version *was* 2.7.6. Now:

```
$ python -V
Python 2.7.10
```

That didn't solve it initially, so I tried reinstalling `compose` and that worked :+1: 

Thanks for the help!
