### ISSUE TITLE
Containers are incorrectly considered part of project on Swarm

### ISSUE THREAD

**Issue by bfirsh** [docker/compose#1470]
```
$ docker run -d nginx
$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                  PORTS               NAMES
82d6b3f424df        nginx:latest        "nginx -g 'daemon of   10 seconds ago      Up Less than a second   80/tcp, 443/tcp     swarm-master/clever_nobel
$ docker-compose up
/Library/Python/2.7/site-packages/requests-2.6.2-py2.7.egg/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Recreating clever_nobel...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.3.0dev', 'console_scripts', 'docker-compose')()
  File "/Users/ben/p/compose/compose/cli/main.py", line 32, in main
    command.sys_dispatch()
  File "/Users/ben/p/compose/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Users/ben/p/compose/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/Users/ben/p/compose/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Users/ben/p/compose/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/Users/ben/p/compose/compose/cli/main.py", line 470, in up
    do_build=not options['--no-build'],
  File "/Users/ben/p/compose/compose/project.py", line 230, in up
    do_build=do_build,
  File "/Users/ben/p/compose/compose/service.py", line 333, in execute_convergence_plan
    for c in containers
  File "/Users/ben/p/compose/compose/service.py", line 380, in recreate_container
    number=container.labels.get(LABEL_CONTAINER_NUMBER),
  File "/Users/ben/p/compose/compose/service.py", line 214, in create_container
    number or self._next_container_number(one_off=one_off),
  File "/Users/ben/p/compose/compose/service.py", line 450, in _next_container_number
    filters={'label': self.labels(one_off=one_off)})
  File "/Users/ben/p/compose/compose/container.py", line 70, in number
    self.short_id, LABEL_CONTAINER_NUMBER))
ValueError: Container 82d6b3f424 does not have a com.docker.compose.container-number label
```

Looks like that nginx container is considered part of the project even though it doesn't have any Compose labels.

**Comment by aanand** [comment]
Swarm 0.2.0 ignores label filters in `ps`, so every container in the cluster is considered part of every Compose app.

It should be fixed in Swarm 0.3.0 - see https://github.com/docker/swarm/pull/738 - so once the first Swarm RC is out, we should check against it to make sure.

ping @vieux, who also reported this.

**Comment by thaJeztah** [comment]
ping @aanand swarm 0.3.0-rc1 is available now for testing: https://github.com/docker/swarm/releases/tag/v0.3.0-rc1

**Comment by kacole2** [comment]
I believe I'm hitting this issue as well and not sure what to do. This is my first time running docker compose. here is my error trail from running this for the first time. I created my swarm cluster by following the directions using `docker run swarm create`. any help is appreciated

```
kcoleman-mbp:ecs-docker kcoleman$ docker-compose up -d
Recreating swarm-agent...
Pulling ecsnode02 (emccode/ecsobjectsw:v2.0)...
swarm-master: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node01: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node02: Pulling emccode/ecsobjectsw:v2.0... : downloaded
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 470, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 333, in execute_convergence_plan
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 380, in recreate_container
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in create_container
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 450, in _next_container_number
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 70, in number
ValueError: Container f9bef6a5b6 does not have a com.docker.compose.container-number label
```

**Comment by kacole2** [comment]
@thaJeztah @aanand @vieux @bfirsh I tried this with Swarm v0.3.0-rc2 and i'm still getting the same thing.
```
ubuntu@swarm-create:~$ sudo docker run swarm:0.3.0-rc2 c
5f50a4602c412ea7d6a397ad11107989
```
I created the swarm cluster using the ID above.

Here is my docker-compose.yml
```
--- 
ecsnode01: 
  environment: 
    - SS_GENCONFIG=1
  image: "emccode/ecsobjectsw:v2.0"
  net: host
  restart: always
  volumes: 
    - "/host:/host"
    - "/var/log/vipr/emcvipr-object:/opt/storageos/logs"
    - "/data:/data:rw"
ecsnode02: 
  environment: 
    - SS_GENCONFIG=1
  image: "emccode/ecsobjectsw:v2.0"
  net: host
  restart: always
  volumes: 
    - "/host:/host"
    - "/var/log/vipr/emcvipr-object:/opt/storageos/logs"
    - "/data:/data:rw"
ecsnode03: 
  environment: 
    - SS_GENCONFIG=1
  image: "emccode/ecsobjectsw:v2.0"
  net: host
  restart: always
  volumes: 
    - "/host:/host"
    - "/var/log/vipr/emcvipr-object:/opt/storageos/logs"
    - "/data:/data:rw"
```

here is the error output:
```
kcoleman-mbp:ecs-docker kcoleman$ docker-compose up -d
Recreating swarm-agent...
Pulling ecsnode02 (emccode/ecsobjectsw:v2.0)...
swarm-master: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node01: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node02: Pulling emccode/ecsobjectsw:v2.0... : downloaded
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 32, in main
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 21, in sys_dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 34, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.docopt_command", line 24, in dispatch
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.command", line 66, in perform_command
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.cli.main", line 470, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 230, in up
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 333, in execute_convergence_plan
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 380, in recreate_container
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 214, in create_container
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.service", line 450, in _next_container_number
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 70, in number
ValueError: Container d180052d16 does not have a com.docker.compose.container-number label
```

**Comment by aanand** [comment]
By what method did you create the Swarm nodes? How did you get each node to use `swarm:0.3.0-rc2`? (Partly asking because I don't know how to do that myself.)

**Comment by kacole2** [comment]
@aanand I'm using docker machine to create the swarm nodes

```
docker-machine -D create --driver amazonec2 --amazonec2-access-key MYKEY --amazonec2-secret-key MYSECRETKEY --amazonec2-vpc-id vpc-MYZONE --amazonec2-instance-type m3.xlarge --amazonec2-root-size 50 --swarm --swarm-master --swarm-discovery token://5f50a4602c412ea7d6a397ad11107989 swarm-master

docker-machine -D create --driver amazonec2 --amazonec2-access-key MYKEY --amazonec2-secret-key MYSECRETKEY --amazonec2-vpc-id vpc-MYZONE --amazonec2-instance-type m3.xlarge --amazonec2-root-size 50 --swarm --swarm-discovery token://5f50a4602c412ea7d6a397ad11107989 swarm-node01

docker-machine -D create --driver amazonec2 --amazonec2-access-key MYKEY --amazonec2-secret-key MYSECRETKEY --amazonec2-vpc-id vpc-MYZONE --amazonec2-instance-type m3.xlarge --amazonec2-root-size 50 --swarm --swarm-discovery token://5f50a4602c412ea7d6a397ad11107989 swarm-node02
```

ip's removed and replaced with `x` and `y`
```
kcoleman-mbp:ecs-docker kcoleman$ docker info
Containers: 4
Strategy: spread
Filters: affinity, health, constraint, port, dependency
Nodes: 3
 swarm-master: 54.XXX.YYY.42:2376
  └ Containers: 2
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 15.42 GiB
 swarm-node01: 54.XXX.YYY.66:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 15.42 GiB
 swarm-node02: 52.XXX.YYY.74:2376
  └ Containers: 1
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 15.42 GiB
```

**Comment by aanand** [comment]
Yeah, my guess would be that creating the discovery token with the right version of Swarm isn't enough to make the nodes use it.

@vieux @ehazlett - how should one create a Swarm cluster using a specific version?

**Comment by ehazlett** [comment]
@kacole2 starting with machine 0.3.0-rc2 you can now specify the version of Swarm for the node.  You can do it via the `--swarm-image` flag.  For example: `--swarm-image=swarm:0.3.0-rc2`.  Note: you will need this for each create command.

**Comment by kacole2** [comment]
@ehazlett you're a bad ass. thanks! that made it work

```
kcoleman-mbp:ecs-docker kcoleman$ docker-compose up -d
Pulling ecsnode02 (emccode/ecsobjectsw:v2.0)...
swarm-master: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node01: Pulling emccode/ecsobjectsw:v2.0... : downloaded
swarm-node02: Pulling emccode/ecsobjectsw:v2.0... : downloaded
Creating ecsdocker_ecsnode02_1...
Creating ecsdocker_ecsnode03_1...
Creating ecsdocker_ecsnode01_1...
```

**Comment by ehazlett** [comment]
@kacole2 hahaha thx ;)

**Comment by aanand** [comment]
I've confirmed manually that this is fixed with Swarm 0.3.0-rc2. I've also started work on automated testing against a Swarm cluster so we catch bugs like this earlier.
