### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by aanand** [docker/compose#1484]
#890 is getting long, so I'm creating this issue to zoom out a bit.

## The Original Problem

On Python versions prior to 2.7.9, urllib3 (and therefore Requests, and therefore Compose) outputs an `InsecurePlatformWarning`, because Python prior to 2.7.9 is insecure, as explained [here](https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning).

(This seems to have been the case since Requests 2.6. Requests 2.6+ is a hard requirement, since anything earlier doesn't work with PyInstaller: https://github.com/kennethreitz/requests/issues/2465)

So anyway, this can be fixed either by **using Python 2.7.9+** or by **using PyOpenSSL**. All explained in that link.

## Using Python 2.7.9+

Python 2.7.9+ exhibits a bug with newer versions of OpenSSL - it exits with a CERTIFICATE_VERIFY_FAILED error, seemingly when attempting to make any request over TLS. This was discovered a while back by users installing Compose via Pip and reported in #890, https://github.com/docker/docker-py/issues/465, https://github.com/Homebrew/homebrew/issues/38226.

If we're going to use Python 2.7.9 to build the binary, it's now an issue for everyone.

Python 2.7.9 works fine with OpenSSL 1.0.1, but Python 2.7.10 complains about missing symbols (for me) unless it's using OpenSSL 1.0.2, which is no good because it exhibits the bug. So the magic combination seems to be **Python 2.7.9 and OpenSSL 1.0.1**.

Now, getting Python 2.7.9 and OpenSSL 1.0.1j running on OS X Mountain Lion (the older OS we use to build the Mac binary so that it works on as many Macs as possible) is working: #1474 

However, getting Python 2.7.9 running on Debian Wheezy (the older distro we use to build the Linux binary so that a widely compatible libc is linked in) is non-trivial, and would seem to entail building from source (since Wheezy's python package is understandably old - 2.7.3). Furthermore, I can't get Pip working. People are welcome to try - have at the `Dockerfile`.

## Using PyOpenSSL

Installing PyOpenSSL via Pip and using it with Compose seems to work just fine ([here's my branch](https://github.com/docker/compose/compare/docker:master...aanand:use-pyopenssl)). Getting it to work with PyInstaller, however, is proving a challenge:

1. I get [an error](https://gist.github.com/aanand/3d992c90a238a1ecdfd5) when attempting to build the Mac binary.
2. While the Linux binary builds successfully, I get [an error](https://gist.github.com/aanand/ee9f4203459900f45b50) when I run it.

**Comment by erwin16** [comment]
ves@MacMini:~$ openssl version
OpenSSL 1.0.1l 15 Jan 2015
yves@MacMini:~$ python --version
Python 2.7.10

$ docker-compose up
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5

**Comment by nfirvine** [comment]
I'm trying to find a working combination for Windows+cygwin+boot2docker.  Looks like I finally found one:
```bash
python --version; python -c 'import ssl; print ssl.OPENSSL_VERSION'; python -c 'import requests; print "request s:", requests.__version__'; boot2docker version; docker-compose --version; ssh -V
Python 2.7.9
OpenSSL 1.0.1k 8 Jan 2015
requests: 2.5.3
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc
docker-compose 1.2.0
OpenSSH_6.7p1, OpenSSL 1.0.1k 8 Jan 2015
```

I had to downgrade cygwin's ssh as well (dependency on openssl).

**Comment by dnephin** [comment]
It seems to me like one solution to these problems might be changing how we package compose. PyInstaller has caused a bunch of problems for us.

We could use something like https://pythonhosted.org/py2app/ for osx, and use a `.deb` and `.rpm` for linux.

**Comment by ain** [comment]
Reproduced as well. :+1: for a reasonable fix.

**Comment by aanand** [comment]
I've built some binaries with the fix in #1474. Please try them out if you've been experiencing SSL issues:

http://cl.ly/3W3a2S3t2c32/download/docker-compose-Linux-x86_64
http://cl.ly/0i00310l3x27/download/docker-compose-Darwin-x86_64

**Comment by hynek** [comment]
As the current maintainer of pyOpenSSL I would recommend to focus on getting pyOpenSSL running even though it means extra dependencies.  Working around the `ssl` module’s problems is much harder and long-winded than with pyOpenSSL and it’s always easier to upgrade a package than a whole interpreter.

As for your problems in the first posting: I don’t know anything about PyInstaller but did you bring your problems to the attention of upstream? At least https://github.com/pyca/cryptography is pretty responsive at fixing problems if it’s on our side.

**Comment by antoineco** [comment]
@aanand I just tried your binary for Linux and the urllib3 warning disappeared.

I doesn't solve the issue described [here](https://github.com/docker/compose/issues/1319) (#1319) though, regarding private repos.

**Comment by aanand** [comment]
@hynek I'd be overjoyed if we could get it running on pyOpenSSL - it's just that I got the other approach working first, and we're on a deadline.

I've created what I think is a minimal failing case here: https://github.com/aanand/pyinstaller-pyopenssl-bug/tree/master

I've also found a discussion on the PyInstaller repo that seems relevant, although they claim it's a Windows-specific issue (I'm seeing it on both OS X Yosemite and Debian Wheezy): https://github.com/pyinstaller/pyinstaller/pull/140

This comment in particular seems relevant, as it namechecks the pyOpenSSL module that can't be found in my stack trace below: https://github.com/pyinstaller/pyinstaller/pull/140#issuecomment-73174437

The stack trace I get when running the binary (which PyInstaller now successfully builds, since updating it to the latest commit on the `develop` branch):

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/OpenSSL", line 8, in <module>
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/OpenSSL.rand", line 11, in <module>
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/OpenSSL._util", line 6, in <module>
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.binding", line 60, in <module>
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.binding", line 109, in Binding
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/cryptography.hazmat.bindings.utils", line 68, in build_ffi_for_binding
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/venv/lib/python2.7/site-packages/PyInstaller/loader/pyi_importers.py", line 276, in load_module
    exec(bytecode, module.__dict__)
  File "/Users/aanand/work/docker/pyinstaller-pyopenssl/build/main/out00-PYZ.pyz/cryptography.hazmat.bindings.openssl.osrandom_engine", line 10, in <module>
IOError: [Errno 2] No such file or directory: '/var/folders/zd/gsd4r7y17wb7qscnkp5xl1q00000gp/T/_MEIbgmytC/cryptography/hazmat/bindings/openssl/src/osrandom_engine.h'
```

**Comment by hynek** [comment]
This seems to be related to pyca/cryptography#1524 . pyOpenSSL itself is a pure Python package as of 0.14 and later so anything involving C/header must come from one of its dependencies.

cc @reaperhulk @alex

**Comment by aanand** [comment]
OK, thanks for digging. If a fix is some ways off - as https://github.com/pyca/cryptography/issues/1524#issuecomment-106681728 suggests - then #1474 is still my preferred solution for now.

**Comment by aanand** [comment]
Closed by #1474.

**Comment by aanand** [comment]
This is fixed in RC2: https://github.com/docker/compose/releases/tag/1.3.0rc2

**Comment by ain** [comment]
Yup, works nicely now with `1.3.0`.

**Comment by ouit0408** [comment]
@nfirvine : I am trying to run Windows+cygwin+boot2docker combination but getting the error 

SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)
while running 'docker-compose up -d ' cmd on cygwin. My parameters are 
Python 2.7.10
OpenSSL 1.0.2c 12 Jun 2015
request s: 2.7.0
Boot2Docker-cli version: v1.7.0
Git commit: 7d89508
docker-compose version: 1.3.1
CPython version: 3.4.3
OpenSSL version: OpenSSL 1.0.2c 12 Jun 2015
OpenSSH_6.9p1, OpenSSL 1.0.2c 12 Jun 2015

Shall I downgrade my OpenSSL ?does that works for you?

**Comment by nfirvine** [comment]
@ouit0408 I'm still getting the CERTIFICATE_VERIFY_FAILED error on boot2docker with the following config:
```bash
$ python --version; python -c 'import ssl; print ssl.OPENSSL_VERSION'; python -c 'import requests; print "request s:", requests.__version__'; boot2docker version; docker-compose --version; ssh -V
Python 2.7.10
OpenSSL 1.0.2c 12 Jun 2015
request s: 2.6.2
Boot2Docker-cli version: v1.6.2
Git commit: cb2c3bc
docker-compose version: 1.3.1
CPython version: 2.7.10
OpenSSL version: OpenSSL 1.0.2c 12 Jun 2015
OpenSSH_6.9p1, OpenSSL 1.0.2c 12 Jun 2015
```

**Comment by nfirvine** [comment]
@ouit0408 And it looks like I can't even downgrade to the 1.0.1k version in cygwin anymore. I've moved onto doing everything in a virtualized linux box so it's not killing me.

**Comment by ouit0408** [comment]
managed to fix the Open SSL error , using the solution given by coderfi https://github.com/docker/compose/issues/890  . I am getting another error when I do docker-compose up 


Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 31, in main
    command.sys_dispatch()
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 21, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 34, in dispatch
    super(Command, self).dispatch(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/compose/cli/docopt_command.py", line 24, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python3.4/site-packages/compose/cli/command.py", line 66, in perform_command
    handler(project, command_options)
  File "/usr/lib/python3.4/site-packages/compose/cli/main.py", line 460, in up
    do_build=not options['--no-build'],
  File "/usr/lib/python3.4/site-packages/compose/project.py", line 226, in up
    for service in services
  File "/usr/lib/python3.4/site-packages/compose/project.py", line 230, in <listcomp>
    do_build=do_build,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 320, in execute_convergence_plan
    do_build=do_build,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 208, in create_container
    insecure_registry=insecure_registry,
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 232, in ensure_image_exists
    self.build()
  File "/usr/lib/python3.4/site-packages/compose/service.py", line 624, in build
    path = six.binary_type(self.options['build'])
TypeError: string argument without an encoding


any idea ??

**Comment by aanand** [comment]
@ouit0408 Compose doesn't work on Python 3 yet.

**Comment by ouit0408** [comment]
my docker-compose file has this line ' #!/usr/bin/python3 ' so I assumed it should work with python3 , will add python2 and try.Thanks

**Comment by ouit0408** [comment]
With python2 I am getting this error now 

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
ImportError: No module named compose.cli.main

I should rather give up :(

**Comment by aanand** [comment]
@ouit0408 You can't just change the Python version in the executable - you'll have to uninstall it and re-install using Python 2. Or just sidestep the whole Python issue and install using the Mac or Linux binary.

**Comment by ouit0408** [comment]
@aanand uninstalled docker-compose and then re-installed it with Python2. Docker-compse is up and running on Cygwin for windows with this hack 

boot2docker ssh
sudo echo 'DOCKER_TLS=no' > /var/lib/boot2docker/profile

then restart boot2docker, i.e.
boot2docker stop
boot2docker start

and something like this to your ~/.bashrc (make sure the ip is correct)

export DOCKER_HOST=tcp://192.168.59.103:2375
unset DOCKER_CERT_PATH
unset DOCKER_TLS_VERIFY

Thanks !

**Comment by barberj** [comment]
My stuff all seems to be working, but i'm getting this

```
/usr/local/Cellar/fig/1.3.1/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```
While running. Did a quick google out of curiosity. Way to silence? I'm using ruby so its not any of the python things mentioned above.

**Comment by aanand** [comment]
@barberj It looks like you've installed Compose using Homebrew, which isn't an officially supported method. Try installing using the OS X binary: http://docs.docker.com/compose/install/

**Comment by beorn** [comment]
Well, not supporting Homebrew is a real drag.  It's pretty stoneage to expect developers to live without package managers.

**Comment by tdsmith** [comment]
FWIW, docker-compose with pyOpenSSL 0.15.1, cryptography 0.9.3, and requests 2.6.2 built against OpenSSL 1.0.2d with Python 2.7.6 seems to give the same failure that you see with Python 2.7.9+ and OpenSSL 1.0.2:

```
tim@rocketman:test$ docker-compose up --allow-insecure-ssl
SSL error: [Errno bad handshake] [('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')]
```

**Comment by keithbentrup** [comment]
@aanand 
I'm having an issue with the 1.6.2 release version os OSX.
```
$~/Downloads/docker-compose ps
ERROR: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```
```
$ ~/Downloads/docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1j 15 Oct 2014
```
The pip version output:
```
$ docker-compose ps
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 56, in main
    command.sys_dispatch()
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/Library/Python/2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 191, in perform_command
    handler(project, command_options)
  File "/Library/Python/2.7/site-packages/compose/cli/main.py", line 377, in ps
    project.containers(service_names=options['SERVICE'], stopped=True) +
  File "/Library/Python/2.7/site-packages/compose/project.py", line 363, in containers
    filters={'label': self.labels(one_off=one_off)})]))
  File "/Library/Python/2.7/site-packages/docker/api/container.py", line 69, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Library/Python/2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/docker/client.py", line 112, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Library/Python/2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```
```
$ docker-compose version
docker-compose version 1.6.2, build 4d72027
docker-py version: 1.7.2
CPython version: 2.7.10
OpenSSL version: OpenSSL 0.9.8zg 14 July 2015
```

I tried with the latest of openssl from brew and reinstalled docker-compose with pip, but the newer version was not reflected in docker-composer version.

Any suggestions?

`docker ps` works fine

**Comment by keithbentrup** [comment]
For anyone landing here via google, I ultimately resolved this issue by uninstalling several packages from brew that I had been using for awhile until some recent change (docker-compose, python, openssl, curl, etc.). I also removed certificate stores at /etc/openssl, /usr/local/etc/openssl, and ensured /System/Library/OpenSSL/certs was empty in an effort to start with a clean slate. I also removed the docker-compose installed via pip. 

Finally, I tried the [1.6.2 release version](https://github.com/docker/compose/releases/tag/1.6.2) and had a new error:  `SSL error: [Errno 2] No such file or directory`. I traced that back to leftover env var `CURL_CA_BUNDLE`. Once I removed that, `docker-compose` worked again. So I don't know specifically what resolved the issue, but it might be good to know for some that there is at least a dependency on curl env settings. HTH someone.

**Comment by trinitronx** [comment]
Ran into this problem on OSX `10.9.5` with the following package versions:

 - Homebrew at `f8cdab7`
 - python: stable 2.7.11
 - openssl: stable 1.0.2g
 - curl: stable 7.48.0
 - docker-compose: stable 1.6.2
 - 


I did the following to resolve:

```
$ brew update
Updated Homebrew from f8cdab7 to 4e8c6e6.

$ brew upgrade openssl curl
Error: openssl 1.0.2g already installed
==> Upgrading 1 outdated package, with result:
curl 7.48.0
==> Upgrading curl
[...SNIP...]

$ brew reinstall python
==> Reinstalling python
[...SNIP...]

$ brew reinstall docker-compose
==> Reinstalling docker-compose
==> Downloading https://homebrew.bintray.com/bottles/docker-compose-1.6.2.mavericks.bottle.tar.gz
[...SNIP...]

$ docker-compose up
/usr/local/Cellar/docker-compose/1.6.2/libexec/vendor/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
ERROR: SSL error: [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version

## Finally, I noticed pip & pycrypto were out of date
$ pip list
[...SNIP...]
pip (8.0.2)
[...SNIP...]
pycrypto (2.6.1)
[...SNIP...]
You are using pip version 8.0.2, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

$ pip install --upgrade pip
Collecting pip
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 277kB/s
Installing collected packages: pip
  Found existing installation: pip 8.0.2
    Uninstalling pip-8.0.2:
      Successfully uninstalled pip-8.0.2
Successfully installed pip-8.1.1

## The following fixed the error after ensuring all packages were up to date
$ pip install --upgrade ndg-httpsclient

Collecting ndg-httpsclient
  Downloading ndg_httpsclient-0.4.0.tar.gz
Collecting PyOpenSSL (from ndg-httpsclient)
  Downloading pyOpenSSL-16.0.0-py2.py3-none-any.whl (45kB)
    100% |████████████████████████████████| 51kB 5.6MB/s
Collecting cryptography>=1.3 (from PyOpenSSL->ndg-httpsclient)
  Downloading cryptography-1.3.1-cp27-cp27m-macosx_10_6_intel.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 573kB/s
Requirement already up-to-date: six>=1.5.2 in /Library/Python/2.7/site-packages (from PyOpenSSL->ndg-httpsclient)
Collecting setuptools>=11.3 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Downloading setuptools-20.7.0-py2.py3-none-any.whl (508kB)
    100% |████████████████████████████████| 512kB 1.9MB/s
Collecting enum34 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Downloading enum34-1.1.2.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 4.0MB/s
Collecting ipaddress (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
  Downloading idna-2.1-py2-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 6.6MB/s
Requirement already up-to-date: cffi>=1.4.1 in /Library/Python/2.7/site-packages (from cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
Requirement already up-to-date: pycparser in /Library/Python/2.7/site-packages (from cffi>=1.4.1->cryptography>=1.3->PyOpenSSL->ndg-httpsclient)
Building wheels for collected packages: ndg-httpsclient, enum34
  Running setup.py bdist_wheel for ndg-httpsclient ... done
  Stored in directory: /Users/jcuzella/Library/Caches/pip/wheels/30/85/40/a29750f9287fe119a10708580a73cfb16f51e5f9a820430a2d
  Running setup.py bdist_wheel for enum34 ... done
  Stored in directory: /Users/jcuzella/Library/Caches/pip/wheels/1a/4e/a5/bc564dd03d9abe991425c88d88aa8c5c99ad9a733551b69b4e
Successfully built ndg-httpsclient enum34
Installing collected packages: setuptools, enum34, ipaddress, pyasn1, idna, cryptography, PyOpenSSL, ndg-httpsclient
  Found existing installation: setuptools 19.4
    Uninstalling setuptools-19.4:
      Successfully uninstalled setuptools-19.4
Successfully installed PyOpenSSL-16.0.0 cryptography-1.3.1 enum34-1.1.2 idna-2.1 ipaddress-1.0.16 ndg-httpsclient-0.4.0 pyasn1-0.1.9 setuptools-20.7.0

$ pip install urllib3[secure]
Collecting urllib3[secure]
  Downloading urllib3-1.15.1-py2.py3-none-any.whl (92kB)
    100% |████████████████████████████████| 102kB 5.8MB/s
Requirement already satisfied (use --upgrade to upgrade): pyOpenSSL>=0.13 in /usr/local/lib/python2.7/site-packages (from urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): certifi in /Library/Python/2.7/site-packages (from urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): ndg-httpsclient in /usr/local/lib/python2.7/site-packages (from urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): pyasn1 in /usr/local/lib/python2.7/site-packages (from urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): cryptography>=1.3 in /usr/local/lib/python2.7/site-packages (from pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /Library/Python/2.7/site-packages (from pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): enum34 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): ipaddress in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): idna>=2.0 in /usr/local/lib/python2.7/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): cffi>=1.4.1 in /Library/Python/2.7/site-packages (from cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Library/Python/2.7/site-packages (from cffi>=1.4.1->cryptography>=1.3->pyOpenSSL>=0.13->urllib3[secure])
Installing collected packages: urllib3
Successfully installed urllib3-1.15.1


## IT WORKS!
$ docker-compose up
Pulling [...SNIP...]

```

Hope this helps!
