### ISSUE TITLE
Compose should allow inherited links from parent configurations

### ISSUE THREAD

**Issue by zdexter** [docker/compose#1819]
The `extends` directive [documentation](https://docs.docker.com/compose/extends/#example) currently states:

> Compose copies configurations from the original service over to the local one, except for links and volumes_from. These exceptions exist to avoid implicit dependencies—you always define links and volumes_from locally. This ensures dependencies between services are clearly visible when reading the current file. Defining these locally also ensures changes to the referenced file don’t result in breakage.

I am not exactly sure what the justification for 'explicit dependencies' is. It's fine if you _want_ to redefine `links` locally in every child configuration, but _having_ to seems like a matter of mere aesthetic preference that collides with some quite common use cases.

Imagine a dev==prod approach, in which various child configurations inherit from a base configuration, with only environment variables and host volumes being different, like so:

    - base.yaml
        - development.yaml
        - staging.yaml # Oops, someone forgot `links` here but no tests caught it
        - production.yaml

I have found that forced-explicit `links` (and `volumes_from`, but to a lesser extent) specification is quite problematic for the following reasons:

1. A developer may omit a `links` specification in a child `.yaml` file, but will not catch it until `production.yaml` is used. In other words, it's hard to test that the `links` specification is correct without actually using a particular configuration. Since one would usually use `development.yaml`, nobody really notices this. If `links` were inherited, one would be testing the values of that directive all the time.
2. `links` is quite likely to be the same in development and production in many common use cases, such as the above. In my compose usage, there is no utility in explicit `links` specification, from an aesthetic perspective - it has simply never been helpful.

Data storage requirements are likely to be different in different environments, so forced specification of `volumes_from` in children, while still weird, is less of a problem in practice.

I think developers should have the _flexibility_ to specify `links` in base configuration files and have `extends` provide the values to children.

**Comment by dnephin** [comment]
I believe this is addressed by #2051

**Comment by zdexter** [comment]
Yes! The new behavior addresses this and is very DRY. Thanks!

**Comment by dnephin** [comment]
@zdexter does http://docs.docker.com/compose/extends/#multiple-compose-files not cover this case?

**Comment by zdexter** [comment]
@dnephin It does, but you still can't inherit links with `extends`. So this isn't useful in the rare case that you run all your containers in all environments.

The `docker-compose.yml` file and the override file have no way to exclude certain containers. So I'm resorting to copying environment-specific files that use `extend` to `docker-compose.yml`. This lets me control which containers run in which environments.

**Comment by dnephin** [comment]
http://docs.docker.com/compose/extends/ has been updated to reflect the different use cases for each. `extends` is now only for sharing partial service config. Using multiple files allows you to share whole services with links.

> The `docker-compose.yml` file and the override file have no way to exclude certain containers

You don't actually need to exclude a service if you structure things in a way where services are only included in the correct environments. If a service doesn't exist in all environments, it won't be in the base `docker-compose.yml`.

If you could provide a more concrete example, I might be able to suggest a setup which makes it work with multiple files.

**Comment by dnephin** [comment]
Either way, I believe this is a duplicate of #1617, so I'm going to close this issue.
