### ISSUE TITLE
Multithreading issue while stopping containers.

### ISSUE THREAD

**Issue by iMerica** [docker/compose#1938]
I have roughly 20-30 containers. This is what I'm starting to see when running `docker-compose stop`

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.utils", line 31, in inner_execute_function
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 203, in <lambda>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 143, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.utils.decorators", line 20, in wrapped
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 815, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 83, in _post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 508, in post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 465, in request
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 573, in send
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 433, in send
ReadTimeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out. (read timeout=70)

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.utils", line 31, in inner_execute_function
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 203, in <lambda>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 143, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.utils.decorators", line 20, in wrapped
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 815, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 83, in _post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 508, in post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 465, in request
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 573, in send
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 433, in send
ReadTimeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out. (read timeout=70)

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 810, in __bootstrap_inner
  File "/compose/build/docker-compose/out00-PYZ.pyz/threading", line 763, in run
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.utils", line 31, in inner_execute_function
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.project", line 203, in <lambda>
  File "/compose/build/docker-compose/out00-PYZ.pyz/compose.container", line 143, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.utils.decorators", line 20, in wrapped
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.client", line 815, in stop
  File "/compose/build/docker-compose/out00-PYZ.pyz/docker.clientbase", line 83, in _post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 508, in post
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 465, in request
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.sessions", line 573, in send
  File "/compose/build/docker-compose/out00-PYZ.pyz/requests.adapters", line 433, in send
ReadTimeout: HTTPSConnectionPool(host='192.168.99.100', port=2376): Read timed out. (read timeout=70)

```

I've truncated the output since it's quite large.

**Comment by iMerica** [comment]
```
$ dc --version                                                                                                                     local_dev_plus/git/master 
docker-compose version: 1.4.0

$ docker-machine --version                                                                                                         local_dev_plus/git/master 
docker-machine version 0.4.1 (e2c88d6)
```

**Comment by aanand** [comment]
I don't know why you're getting a timeout issue, but the bad handling of the exception was fixed in https://github.com/docker/compose/pull/1879. It'll go out in Compose 1.4.1.

**Comment by karlkfi** [comment]
I've been having the same problem, even when the docker daemon is localhost. Worse, the process hangs indefinitely afterwards. Hopefully #1879 fixes the hanging, but the timeout is likely still a problem.

Here's my logs: https://gist.github.com/karlkfi/a7b34c3d35df2e6a975d

If it helps, here's the compose file: https://github.com/kubernetes/kubernetes/blob/master/cluster/mesos/docker/docker-compose.yml

**Comment by vallettea** [comment]
Same problem here.
