### ISSUE TITLE
Windows Build of RC 1.5 Runtime Error

### ISSUE THREAD

**Issue by blaggacao** [docker/compose#2216]
error code: R6043
"An application has made the attempt to load a C runtime library incorrectly."

**Comment by dnephin** [comment]
Please provide us some more details so we can attempt to reproduce the issue:
* windows version
* the command you ran
* how you installed docker-compose

Thanks!

**Comment by blaggacao** [comment]
occurence: `docker-compose`

installation: `wget -O $PATH/docker-compose.exe https://github.com/docker/compose/releases/download/1.5.0rc1/docker-compose-Windows-x86_64.exe`

Windows Version: Windows 10 Education

![image](https://cloud.githubusercontent.com/assets/7548295/10568302/c4f456e4-75db-11e5-8683-54a19aa3f03c.png)

**Comment by janwidmer** [comment]
I am expriencing the same error on Windows 8.1

**Comment by dnephin** [comment]
I did some digging on this error. It sounds like this is a pretty general error, but is known to happen for a few reasons with pyinstaller (what we use to build the `exe`).

https://github.com/pyinstaller/pyinstaller/issues/1516 has a pretty good summary of common scenarios which  trigger the error.

Are either of you renaming the executable? That seems to be a common issue.  For now maybe create a link or a script to call it, instead of renaming it?


It sounds like this issue was fixed (or at least a workaround was provided in  https://github.com/pyinstaller/pyinstaller/commit/28867f6dfe272f50e76458a7e10e552140c866b5) in the 3.0 release. We need to upgrade to this version anyway, so I can see if that fixes the issue.


If the issue is not renaming, is there anything else in that linked issue that sounds related to your setup?

**Comment by janwidmer** [comment]
I was renaming it to "docker-compose.exe" I just tried it with only downloading the file from https://github.com/docker/compose/releases/download/1.5.0rc1/docker-compose-Windows-x86_64.exe and run it without renaming, but I am still getting the error..

**Comment by blaggacao** [comment]
Yes, in my case y stripped off the `-Windows*` part. but also using a freshly downloaded bnary without renaming reproduces the error...

**Comment by janwidmer** [comment]
I read the comment from the ticket you mentioned at pyinstaller, but I dont see any thing relating to my setup. Weird enough, it seems to be working on my colleagues laptop also running Windows 8.1..

Any timeline, when 3.0 will be released?

**Comment by dnephin** [comment]
Oh, I think we actually rename it in our build script, oops.  I think the original name was actually `docker-compose` (without the .exe). Are you able to run it that way (just to confirm this is the issue) ?

The pyinstaller 3.0 release looks like it was done a couple weeks ago, so we should be able to upgarde to it now. Hopefully that will resolve the issue.

I was also able to run the binary with `wine` so I'm not sure why renaming is only an issue sometimes.

**Comment by dnephin** [comment]
After #2245 is merged we'll see if this is resolved or if there is something else we need to do.

**Comment by blaggacao** [comment]
>Are you able to run it that way (just to confirm this is the issue) ?

I confirm, got call! :smile: 

Renaming it to `docker-compose` without `.exe` resolves the issue.

**Comment by dnephin** [comment]
Ok great! There's a good chance the pyinstall upgrade is going to fix this.  I'll get it into an rc2 soon.

**Comment by dnephin** [comment]
The binary built using python3 is available here: https://ci.appveyor.com/project/docker/compose/build/master-279/artifacts. If you have a minute to try it out, it would be great to confirm this fixes the issue.  You can try renaming it as well, to confirm.

**Comment by blaggacao** [comment]
I can confirm, either `docker-compose.exe` or `docker-compose-Windows-x86_64.exe` works. Closing. Thank you!

**Comment by janwidmer** [comment]
I can also confirm, that 

1. removing the ".exe" on the old version works
2. the new version with pyinstaller 3.0 works with ".exe"

Thanks and best regards
jan
