### ISSUE TITLE
Add --quiet or --silent option to docker-compose

### ISSUE THREAD

**Issue by dkirrane** [docker/compose#3447]
I'm trying to assign the output of `docker-compose run` to a variable in bash.

Currently docker-compose run can print to console stuff like:

```
docker-compose run serviceabc ls
WARNING: The MVN_OPT variable is not set. Defaulting to a blank string.
Starting serviceabc
dir1
dir2
dir3
```

Can a `-s` `--silent` or `-q` `--quiet` option be added to `docker-compose run` avoid printing anything other than the command output.

I guess this would also make sense for other `docker-compose` commands too.

**Comment by shin-** [comment]
You can redirect stderr to `/dev/null` (i.e. `2>/dev/null`), which should have that exact effect.

**Comment by elliotchance** [comment]
@shin- The quiet option is different from just sending all output nowhere, perhaps it's better explained as "don't show progress bars".

There should be an option that still shows a build steps, but not the actual progress bars which spray a huge amount of output on CI servers since the docker commands expect that your using a terminal that has the control codes to write over previous lines.

**Comment by shin-** [comment]
@elliotchance That seems to be a different request from the one made by the original poster. Can you create a separate issue for it?

**Comment by elliotchance** [comment]
@shin- thanks for letting me know :) #3770

**Comment by jbarciauskas** [comment]
I'd specifically be interested in an option to quiet the download progress update, as it pollutes the travis logs

**Comment by lelit** [comment]
Redirecting stderr works, but potentially hides real errors too, so I think adding --quiet would be better.

**Comment by RealSalmon** [comment]
+1

I would find this useful as well. Redirecting stderr is an *OK* workaround, but it has caused me some minor frustration as it hides actual errors.

**Comment by Bamieh** [comment]
do we have any updates on this issue?

**Comment by jbarciauskas** [comment]
This should have been fixed and released in 1.15? https://github.com/docker/compose/pull/4730

**Comment by lelit** [comment]
Only for `pull`, AFAICT.

**Comment by shin-** [comment]
Fixed with the addition of `--log-level` in #5703

**Comment by charlesreid1** [comment]
Note that `--log-level` should come before `up`, so up doesn't steal the flag, e.g.,

```
$ docker-compose --log-level ERROR up -d --build
```

**Comment by Vanav** [comment]
It is not fixed:
```
# docker-compose --log-level CRITICAL restart container

Restarting compose_container_1 ... done
```

**Comment by iabotsiTC** [comment]
Same here, still getting warnings even though setting `--log-level ERROR `:
```
WARNING: no logs are available with the 'none' log driver
```

And `docker-compose version` is 1.21.1...
Any idea?

**Comment by 4rthem** [comment]
Dependencies are also printed out in the `run` command:

```
$ docker-compose --log-level ERROR run my_service command.sh
Starting linked_container_1 ... done
```

I believe this issue should be reopened.

**Comment by phillip-elm** [comment]
@shin- Any word on this? It's been two and a half years since this issue was opened. Piping to stderr should not be the only solution to this problem.

I second that this issue should be reopened.

**Comment by phillip-elm** [comment]
@shin- Any word on this?

**Comment by shin-** [comment]
Current issues with `--log-level` are tracked separately: #6026
