### ISSUE TITLE
missing dependency on MAC 

### ISSUE THREAD

**Issue by huanyu-liao** [docker/compose#4436]
I type the following command to start a docker compose file, and get the following error

docker-compose up
Traceback (most recent call last):
  File "/Users/leo/anaconda/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/Users/leo/anaconda/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/Users/leo/anaconda/lib/python2.7/site-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/Users/leo/anaconda/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname

**Comment by shin-** [comment]
`pip install 'backports.ssl_match_hostname>=3.5'`

**Comment by shin-** [comment]
To avoid that problem in the future, you should probably update `pip` as well. The dependency should be resolved properly by a newer version of the package installer.

**Comment by huanyu-liao** [comment]
@shin- 
pip install 'backports.ssl_match_hostname>=3.5'
Requirement already satisfied: backports.ssl_match_hostname>=3.5 in /Users/leo/anaconda/lib/python2.7/site-packages

I already update this library. but it still doesn't work and get the error I posted

**Comment by henres** [comment]
Same here, have the same problem on ubuntu 16.10 with backports.ssl-match-hostname (3.5.0.1) installed
```
docker-compose --version
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 7, in <module>
    from compose.cli.main import main
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 17, in <module>
    from . import errors
  File "/usr/lib/python2.7/site-packages/compose/cli/errors.py", line 10, in <module>
    from docker.errors import APIError
  File "/usr/lib/python2.7/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python2.7/site-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/lib/python2.7/site-packages/docker/utils/__init__.py", line 2, in <module>
    from .utils import (
  File "/usr/lib/python2.7/site-packages/docker/utils/utils.py", line 19, in <module>
    from .. import tls
  File "/usr/lib/python2.7/site-packages/docker/tls.py", line 5, in <module>
    from .transport import SSLAdapter
  File "/usr/lib/python2.7/site-packages/docker/transport/__init__.py", line 3, in <module>
    from .ssladapter import SSLAdapter
  File "/usr/lib/python2.7/site-packages/docker/transport/ssladapter.py", line 21, in <module>
    from backports.ssl_match_hostname import match_hostname
ImportError: No module named ssl_match_hostname
```
