### ISSUE TITLE
docker compose does not honor build arg while docker-compose does

### ISSUE THREAD

**Issue by princemaple** [docker/compose#8329]
## Description of the issue

Not sure if it's the right place to post this issue.
`docker compose build` does not honor build arg like `docker-compose` does

## Context information (for bug reports)

**Output of `docker-compose version`**
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Output of `docker version`**
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker-compose config`**
(Make sure to add the relevant `-f` and other flags)
```
services:
  app:
    build:
      args:
        MIX_ENV: dev
     ....
```

## Steps to reproduce the issue

1. docker compose build app
2. docker-compose build app

### Observed result

1. it's not passing arg properly, MIX_ENV gets default `prod`
2. gets `dev` properly

### Expected result
works the same

### Stacktrace / full error message

```
N/A
```

## Additional information

win10
docker for win

**Comment by cdemulde** [comment]
I think this might be related to this problem (specifically for IPv4 addresses): https://stackoverflow.com/questions/67318361/docker-compose-ignoring-ipv4-address-in-container, that I just bumped into myself as well (on macOS Catalina):

docker-compose version:
```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

docker version:
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by princemaple** [comment]
Building with explicit --build-arg works as expected.

**Comment by daverin** [comment]
Found this issue on MacOS

Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by nielspedersen** [comment]
I am also seeing this issue on  macOS Mojave 10.14.6 (18G6020)

``` 
$ docker --version
Docker version 20.10.5, build 55c4c88
$ docker-compose --version
docker-compose version 1.29.0, build 07737305
```

I can not build the image with `docker compose build ...` since my build relies on some build args for dependency installation. I *can*, however, build it using `docker-compose build ...` 🤷

**Comment by empz** [comment]
Jesus christ I've wasted 2 hours trying to figure it why my args weren't working. I thought I was doing something wrong. I was using "docker compose" the whole time.

It happens on Windows 10 inside WSL2 (Ubuntu 20.04).

**Comment by princemaple** [comment]
The issue in compose-cli has been closed. I guess the fix has been released in desktop 3.4.0

**Comment by JonathanHolvey** [comment]
> The issue in compose-cli has been closed. I guess the fix has been released in desktop 3.4.0

Yes, the build args are now working as expected with `docker compose build` on Docker Desktop 3.4.0

**Comment by KES777** [comment]
Still does not work:
```
services:
  invoice:
    build:
      context: ../app
      dockerfile: ./Dockerfile
      args:
        progress: plain
```

`docker compose up --build`

**Comment by HermantNET** [comment]
This still doesn't work, at least when running on WSL2 (Ubuntu 20.04)

**Comment by MikeStankavich** [comment]
Observed that `docker compose build` works as expected but `docker compose up --build` does not as noted by @KES777  and @HermantNET. I'm running Docker Compose version v2.15.1 on MacOS Ventura 13.2.1.
