### ISSUE TITLE
Docker-compose no longer gracefully stops

### ISSUE THREAD

**Issue by cchantep** [docker/compose#8523]
### Expected behavior

Successful graceful shutdown of `docker-compose`

### Actual behavior

All containers are stopped, but compose is hanging on forever until we are forced to kill it.

```
Gracefully stopping... (press Ctrl+C again to force)
[+] Running 7/7
 ⠿ Container PRJ-dev_spark-worker_1          Stopped                                                          11.3s
 ⠿ Container PRJ-dev_spark-master_1          Stopped                                                          12.2s
 ⠿ Container PRJ-dev_kafka-schemaregistry_1  Stopped                                                          11.3s
 ⠿ Container PRJ-dev_mongodb_1               Stopped                                                          12.3s
 ⠿ Container PRJ-dev_object-storage_1        Stopped                                                           1.7s
 ⠿ Container PRJ-dev_kafka_1                 Stopped                                                           4.3s
 ⠿ Container PRJ-dev_zookeeper_1             Stopped                                                          11.4s
```

(hanging forever ...)

```
^CERRO[3631] got 3 SIGTERM/SIGINTs, forcing shutdown      
[+] Running 0/0
 ⠿ Container PRJ-dev_mongodb_1               Error while Killing                                               0.0s
 ⠿ Container PRJ-dev_spark-worker_1          Error while Killing                                               0.0s
 ⠿ Container PRJ-dev_object-storage_1        Error while Killi...                                              0.0s
 ⠿ Container PRJ-dev_spark-master_1          Error while Killing                                               0.0s
 ⠿ Container PRJ-dev_kafka-schemaregistry_1  Error while...                                                    0.0s
 ⠿ Container PRJ-dev_kafka_1                 Error while Killing                                               0.0s
 ⠿ Container PRJ-dev_zookeeper_1             Error while Killing  
```

### Information

  - macOS Version: 10.15.7
  - Intel core i7
  - Docker Desktop version: 3.5.1 (3.5.1.7)
  - Docker Compose version: 2.0.0-beta.4

### Steps to reproduce the behavior

- On a fresh Docker Desktop (after data purge), `docker-compose -f any-conf.yml up`
- Once everything is up, `Ctrl+C` to gracefully stop

**Comment by Radiergummi** [comment]
This also occurs on my machine if `restart: unless-stopped` is used; same setup as OP, latest Docker Desktop on Mac. This is pretty annoying.
![Bildschirmfoto 2021-11-16 um 10 54 41](https://user-images.githubusercontent.com/6115429/141963117-7ceed211-f921-4d0f-aeb3-73303a95009e.png)

**Comment by cchantep** [comment]
Still not fix. I can hardly lobby for the new Docker plan with such issues.

**Comment by ndeloof** [comment]
Have you tried using v2.2.0?
AFAICT this has been fixed by https://github.com/docker/compose/pull/8926

**Comment by mofux** [comment]
I'm still seeing this error with v2.2.0 on Linux.

```
$ docker-compose --version
Docker Compose version 2.2.0
$ docker --version
Docker version 20.10.11, build dea9396e18
```

```
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 2/2
 ⠿ Container app-core-app_core-1  Stopped                                                                                                                  0.3s
 ⠿ Container app-core-postgres-1      Stopped                                                                                                                  0.3s
[+] Running 0/0
 ⠿ Container app-core-app_core-1  Error while Killing                                                                                                      0.0s
 ⠿ Container app-core-postgres-1      Error while Killing 
```

**Comment by fvdnabee** [comment]
Seeing the same issue as @mofux here, I have to `kill -9` the docker-compose process
`
$ docker-compose --version
Docker Compose version 2.2.0
$ docker --version
Docker version 20.10.11, build dea9396e18
`

**Comment by DevDavido** [comment]
Having the same issue with docker compose since I updated Docker Desktop for Mac from 4.2 to 4.3. All container stopped successfully, but the command is hanging then and forcing the shutdown then produces output `Error while Killing` for every container.

- Docker Compose version v2.2.1
- Docker version 20.10.11, build dea9396

**Comment by top4ek** [comment]
Having the same with Compose 2.2.2 and Docker 20.10.11 on Archlinux.

**Comment by twitchax** [comment]
+1, Similar issue with Docker Desktop for Windows 4.3.

**Comment by artursudnik** [comment]
Same here on MacOS:
![image](https://user-images.githubusercontent.com/2759741/145203531-62e92270-df5c-44dc-a2ff-45a0ed9d9f4f.png)

**Comment by GiacobboNicola** [comment]
+1 same problem after upgrading to docker 20.10.12 and docker-compose 2.2.2 (on a archlinux machine).

**Comment by marcefr** [comment]
+1 same problem here with ubuntu 20.4.3, docker-ce 20.10.12 and docker-compose 2.2.2. Ctrl-C doesn't stop compose if run without -d. Downgrade to 1.29.2 solved it

**Comment by harmonikas996** [comment]
+1 same problem

OS: **Windows 10**
Docker Engine **v20.10.11**
Docker Desktop Docker Desktop **4.3.2 (72729)**
Using **WSL 2**

**Comment by nodejsdeveloperskh** [comment]
I face the same problem in Manjaro. 
docker-compose.yml
```yaml
version: "3.7"

services:
  api-dev:
    image: ${COMPOSE_PROJECT_NAME}-dev:latest
    container_name: "${COMPOSE_PROJECT_NAME}-dev-${APP_NAME}"
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
        volume:
          nocopy: true
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "${DEBUGGING_PORT}:${DEBUGGING_PORT}"
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
```

and Dockerfile
```Dockerfile
# Installation stage
FROM node:16.13-alpine as copy_stage

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm config set registry https://registry.npmjs.org/ && npm config set maxsockets 20
RUN npm ci --loglevel verbose

# Creating isolated image with the installed pacakges inside node_modules
FROM node:16.13-buster

RUN mkdir -p /app && chown -R 1000:1000 /app

WORKDIR /app

ENV NODE_PATH=/usr/local/lib/node_modules/

COPY --chown=1000:1000 --from=copy_stage /app .

EXPOSE ${APP_PORT}
EXPOSE ${DEBUGGING_PORT}

USER 1000:1000

CMD [ "npm", "run", "start:dev" ]
```

`docker version` command output:
```cmd
Client:
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.17.3
 Git commit:        dea9396e18
 Built:             Sat Nov 20 12:57:52 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.3
  Git commit:       847da184ad
  Built:            Sat Nov 20 12:57:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.8
  GitCommit:        1e5ef943eb76627a6d3b6de8cd1ef6537f393a71.m
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
`uname -a` command output:
```cmd
Linux kasir 5.10.84-1-MANJARO #1 SMP PREEMPT Wed Dec 8 09:50:30 UTC 2021 x86_64 GNU/Linux
```
My docker container up and run successfully but It cannot stop containers gracefully and I have to press `ctrl + c` twice.

**Comment by lekhnath** [comment]
I am also facing the exact same problem on Manjaro Linux with the docker-compose version 2.2.2 . This only happens when there is restart option set to any of the services.

**Comment by bgalvao** [comment]
+1
- Manjaro 21.2.0
- Docker version 20.10.11, build dea9396e18
- Docker Compose version 2.2.2
- can confirm that this only happens when there is restart option set to any of the services

**Comment by marcelarie** [comment]
Docker compose up never closes. If I do Cntrl+C twice its shows `Error while killing` 

```logs
[+] Running 6/6
 ⠿ Container dev_manager  Stopped                                                                                                               0.0s
 ⠿ Container dev_mongo    Stopped                                                                                                               0.5s
 ⠿ Container eproduct     Stopped                                                                                                               0.5s
 ⠿ Container dev_master   Stopped                                                                                                               0.0s
 ⠿ Container esearch      Stopped                                                                                                              10.3s
 ⠿ Container dev_redis    Stopped                                                                                                               0.4s
```
```logs
[+] Running 0/0
 ⠿ Container esearch      Error while Killing                                                                                                   0.0s
 ⠿ Container dev_mongo    Error while Killing                                                                                                   0.0s
 ⠿ Container dev_redis    Error while Killing                                                                                                   0.0s
 ⠿ Container dev_manager  Error while Killing                                                                                                   0.0s
 ⠿ Container eproduct     Error while Killing                                                                                                   0.0s
 ⠿ Container dev_master   Error while Killing                                                                                                   0.0s
```

Using `Arch Linux` with kernel `5.15.12-arch1-1`
docker: `5.15.12-arch1-1`
docker-compose: `Docker Compose version 2.2.2`

**Comment by ulyssessouza** [comment]
Hello everybody,

Sorry for the "end of the year delay".
This issue has been fixed by #9019 and version `2.2.3` will be released soon.

**Comment by designermonkey** [comment]
@ulyssessouza will this create a new update for Docker Desktop (Mac) as mine says it is fully up to date (`4.3.2 (72729)`) yet only has `v2.2.1` for `docker compose`?

**Comment by ulyssessouza** [comment]
@designermonkey This will be included in the next version of Docker Desktop.

**Comment by thomashbrnrd** [comment]
Similar issue here on MacOS using an M1 chip.
<img width="714" alt="image" src="https://user-images.githubusercontent.com/17519882/156760362-9c9dfed3-f7fe-4de8-b1d2-d87ac7887bc2.png">
<img width="872" alt="image" src="https://user-images.githubusercontent.com/17519882/156760429-35f1bfa2-ebf0-4f5d-8268-8a83732b05d1.png">

**Comment by DD-coding** [comment]
Problem still exists for me too.

- Docker Compose version v2.2.3
- Docker Desktop 4.5.0 (74594)
- macOS Catalina 10.15.1

But it looks like only my `postgres:12` service is affected.
As soon as I remove `restart: unless-stopped` it works fine.

**Comment by ndeloof** [comment]
@DD-coding I'm using this compose file, trying to reproduce this issue:
```yaml
services:
  pg:
    image: postgres:12
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
```

.. but everything works as expected for me
```console
$ docker compose up
[+] Running 1/1
 ⠿ Container truc-pg-1  Recreated                                                                                                                     0.1s
Attaching to truc-pg-1
truc-pg-1  | The files belonging to this database system will be owned by user "postgres".
...
^CGracefully stopping... (press Ctrl+C again to force)
[+] Running 1/1
 ⠿ Container truc-pg-1  Stopped                                                                                                                       0.2s
canceled
```

**Comment by DD-coding** [comment]
@ndeloof I tested it by adding `unless-stopped` again. But the error does **not** immediately reappear.
Maybe it is some other underlying issue. But it seems so fitting as the error appears the first time after updating Docker Desktop 🤔 
I'll further investigate. Sorry for bothering.

**Comment by abdifitahabdulkadir** [comment]
I solved the issue by removing all Images first, then volumes and containers. also I updated my docker to latest version.
